version: "3.7"

services:
  webserver:
    image: nginx
    container_name: Nginx-WebServer-Container
    ports:
      - "5000:80/tcp"
    volumes:
      - ./nginx/nginx_nohttps_for_test.conf:/etc/nginx/nginx.conf
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.80
    # depends_on:
    #   - frontendvscode, mongodb, backend
  
  frontend:
    image: qmcgaw/reactdevcontainer
    container_name: Frontend-Dev-Container
    command:
      - -c 
      - cd /workspace && npm install --save && npm run dev
    volumes:
      - ./:/workspace
      # Docker
      - ~/.docker:/root/.docker:z
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      - ~/.ssh:/root/.ssh:z
    environment:
      - TZ=
    ports:
      - 3000:3000/tcp
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.81
    
  mongodb:
    image: mongo:latest
    container_name: Mongodb-Container
    ports:
      - "27017:27017"
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.82
  
  backend:
    image: golang:1.18.3-bullseye
    container_name: Backend-Container
    volumes:
      - ../projmural-backend/:/workspace
    ports:
      - "8081:8081"
    command: 
      - /bin/bash
      - -c 
      - cd /workspace && go env -w GOPROXY=https://goproxy.cn,direct && go run main.go --env=docker
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.83

  sharedb:
    build: ./server
    container_name: Sharedb-Container
    ports:
      - "8080:8080" 
      - "8000:8000"
    volumes:
      - ./:/ProjMural
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.84

# 定义网络
networks:
  reverseProxy_service_net:
    ipam:
      config:
        - subnet: 123.115.107.0/24
