version: "3.7"

services:
  webserver:
    image: nginx
    container_name: Nginx-WebServer-Prod-Container
    ports:
      - "5000:80/tcp"
    volumes:
      - ./nginx/nginx_nohttps_for_test.conf:/etc/nginx/nginx.conf
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.80
    # depends_on:
    #  - frontendvscode, mongodb, backend
  
  frontend:
    build: .
    container_name: Frontend-Prod-Container
    ports:
      - 3000:3000/tcp
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.81
    
  mongodb:
    image: mongo:latest
    container_name: Mongodb-Prod-Container
    ports:
      - "27017:27017"
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.82
  
  backend:
    build: ../projmural-backend
    container_name: Backend-Prod-Container
    ports:
      - "8081:8081"
    volumes:
      - ../projmural-backend/:/ProjMural
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.83

  sharedb:
    build: ./server
    container_name: Sharedb-Prod-Container
    ports:
      - "8080:8080" 
      - "8000:8000"
    volumes:
      - ./:/ProjMural
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.84

# 定义网络
networks:
  reverseProxy_service_net:
    ipam:
      config:
        - subnet: 123.115.107.0/24
