version: "3.7"

services:
  webserver:
    image: nginx
    container_name: Nginx-Container
    ports:
      - "5000:80/tcp"
    volumes:
      - ./nginx/nginx_nohttps_for_test.conf:/etc/nginx/nginx.conf
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.80
  
  frontend:
    image: node:14.17
    container_name: Frontend-Container
    volumes:
      - ./:/workspace
    ports:
      - 3000:3000/tcp
    command: 
      - /bin/bash
      - -c 
      - cd /workspace && npm install && npm run start
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.81

  mongodb:
    image: mongo:latest
    container_name: Mongodb-Container

    ports:
      - "27017:27017"
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.82
  
  backend:
    image: golang:1.18.3-bullseye
    container_name: Backend-Container
    volumes:
      - ../projmural-backend/:/workspace
    ports:
      - "8081:8081"
    command: 
      - /bin/bash
      - -c 
      - cd /workspace && go env -w GOPROXY=https://goproxy.cn,direct && go run main.go --env=docker
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.83

  sharedb:
    image: node:14.17
    container_name: Sharedb-Container
    volumes:
      - ./server/:/workspace
    ports:
      - "8080:8080" 
      - "8000:8000"
    command: 
      - /bin/bash
      - -c 
      - cd /workspace && npm install && npm run start
    networks:
      reverseProxy_service_net:
        ipv4_address: 123.115.107.84

# 定义网络
networks:
  reverseProxy_service_net:
    ipam:
      config:
        - subnet: 123.115.107.0/24
